spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop  # MVCC = TRUE란 여러개가 접근했을때 빨리 처리(권장)
    username: sa
    password: 123
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
      #      show_sql: true  # sout으로 SQL이 찍힌다.
      format_sql: true

logging.level:
  org.hibernate.SQL: debug  # hirbernate, Jpa가 생성하는 sql문이 "로그"로 찍힌다.
#  org.hibernate.type: trace

